### ISSUE TITLE
"They throws the frisbee to themself."

### ISSUE THREAD

**Issue by atalii** [Xe/pronouns#2]
Neither option ("They throw the frisbee between themself." or "They throws the frisbee to themself") looks right. I (native English speaker, uses they/.../themself for myself) will naturally say "They throw the frisbee to themself". If I don't think about it, I use the the singular themself but conjugate it as though it were plural.

Anyway English is a mess and idk if a clean solution really exists. [The archived pronoun.is](https://web.archive.org/web/20220317223649/pronoun.is/they/.../themself) uses past tense, which solves the issue at least in this case. ("They threw the frisbee between themselves" and "They threw the frisbee to themself" are both correct.) I don't know enough about grammar to say whether or not that's a general solution (can a past-tense verb conjugation change depending on the plurality of the subject? I have no idea!), but I *think* it works.

Worth noting that fixing this with a `s/throw(s?)/threw/` would cause merge conflicts with #1, so pick whichever you want to deal with first ig, lol

**Comment by Xe** [comment]
Closed in https://github.com/Xe/pronouns/commit/99c4aa2f88f629a268ca8e02419355612c039af0

I hate english lol
